version: "2"
services:
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    working_dir: /client/src/app # sets working directory to app but why?
    volumes:
      - ./client:/client/src/app # map client to client src app
    entrypoint: ["npm", "start"] #override entry point
    links:
      - api #https://docs.docker.com/compose/compose-file/compose-file-v3/#links, not required, but does allow direct contact; like depends on
    networks:
      - webappnetwork
  api:
    build: ./api
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./api:/api  #move in everything.
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge